pipeline{
    agent any
    environment{
        MAVEN_HOME= tool "maven"
        SERVICE_NAME = "identity-service"
        SERVICE_PATH = "services/identity-service"
        DOCKER_IMAGE = "kamleshyadav875/identity-service"
    }
    stages{
        stage("Clone Code from GitHub"){
            steps{
                git url: "https://github.com/KamleshYadav875/foodflow-microservice.git", branch: "main"
            }
        }
        stage("Build Shared Contracts") {
            steps {
                dir("services/event-contracts") {
                    sh "$MAVEN_HOME/bin/mvn clean install -DskipTests"
                }
            }
        }
        stage("Build & Compile"){
            steps {
                dir("${SERVICE_PATH}") {
                    sh "$MAVEN_HOME/bin/mvn clean compile -DskipTests"
                }
            }
        }
        stage("SonarQube Quality Analysis"){
            steps{
                dir("${SERVICE_PATH}") {
                    withSonarQubeEnv("Sonar"){
                        sh "$MAVEN_HOME/bin/mvn sonar:sonar -Dsonar.projectKey=foodflow-identity-service"
                    }
                }
            }
        }
        stage("Build & Package"){
            steps {
                dir("${SERVICE_PATH}") {
                    sh "$MAVEN_HOME/bin/mvn clean package -DskipTests"
                }
            }
        }
        stage("Build Docker Image"){
            steps{
                dir("${SERVICE_PATH}") {
                    sh "ls -la target"
                    sh "docker build -t ${DOCKER_IMAGE}:latest ."
                }
            }
        }
        stage("Deploy to Minikube") {
            steps {
                sh """ kubectl apply -k ${SERVICE_PATH}/k8s/overlay/local \
                --validate=false"""
            }
        }
    }
    post {
        success {
            echo "✅ ${SERVICE_NAME} Build and Sonar Analysis done"
        }
        failure {
            echo "❌ ${SERVICE_NAME} pipeline failed"
        }
    }
}